strict: true

site_name: Various Complements
repo_url: https://github.com/tadashi-aikawa/obsidian-various-complements-plugin
edit_uri: https://github.com/tadashi-aikawa/docs-obsidian-various-complements-plugin/edit/main/docs/

theme:
  name: "material"
  icon:
    logo: material/keyboard
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress

extra_css:
  - main.css

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - glightbox
  - backlinks_section:
      title: "🖇️ Backlinks"
      description: ""
      add_to_toc: false
      hide_if_empty: true
  - git-revision-date-localized:
      strict: false
      enable_creation_date: true
      timezone: Asia/Tokyo
  - git-authors:
      strict: false
      show_email_address: false
